<?php
/**
 * Terms of service. Meta asks for a terms URL alongside the privacy
 * policy at App Review.
 *
 * Starting template only - have a lawyer review it and fill in COMPANY_*
 * in .env before relying on it.
 */

require __DIR__ . '/../config/bootstrap.php';
require __DIR__ . '/partials/legal_placeholder.php';

$updated = 'August 4, 2026';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Terms of Service — AfterburnerX</title>
<link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
<?php include __DIR__ . '/partials/nav.php'; ?>
<main class="container narrow">
  <h1>Terms of Service</h1>
  <p class="muted small">Last updated: <?= htmlspecialchars($updated) ?></p>

  <?php if (!legal_is_configured()): ?>
    <p class="alert">
      These terms still contain unfilled placeholders. Set the
      <code>COMPANY_*</code> values in <code>.env</code> and have the text
      reviewed by a lawyer before submitting for Meta App Review.
    </p>
  <?php endif; ?>

  <div class="card">
    <h2>The service</h2>
    <p>
      AfterburnerX, operated by <?= legal_value('COMPANY_NAME', 'Company name') ?>,
      lets you connect Facebook Pages and Instagram Business accounts you
      control, publish posts to them immediately or on a schedule, and
      generate AI advertising suggestions.
    </p>

    <h2>Your account</h2>
    <p>
      You are responsible for keeping your password secure and for all
      activity under your account. Anyone with access to your account can
      publish to your connected Pages, so use a strong, unique password.
    </p>

    <h2>Your responsibilities</h2>
    <ul>
      <li>You may only connect accounts and Pages you own or are authorised to manage.</li>
      <li>You are responsible for the content you publish through the service, including its legality and any rights in images you upload.</li>
      <li>You must comply with the platform rules of the networks you post to, including Meta's Terms of Service, Community Standards, and Platform Policy.</li>
      <li>You may not use the service for spam, harassment, or to publish unlawful content.</li>
    </ul>

    <h2>Scheduling is best-effort</h2>
    <p>
      Scheduled posts are published by a background worker. Publishing can be
      delayed or fail for reasons outside our control — expired access tokens,
      Meta rate limits or outages, or content Meta rejects. Failed posts are
      retried a limited number of times and then marked as failed, visible on
      your posts page. We do not guarantee that any given post is published at
      an exact time, or at all.
    </p>

    <h2>AI suggestions</h2>
    <p>
      Advertising suggestions are generated by an AI model and are provided as
      ideas only. They may be inaccurate or unsuitable for your business. Review
      them before acting, and do not treat them as professional marketing,
      legal, or financial advice.
    </p>

    <h2>Third-party platforms</h2>
    <p>
      We are not affiliated with or endorsed by Meta Platforms, Inc. Facebook
      and Instagram are trademarks of Meta. Access to those platforms depends on
      Meta's APIs and policies, which can change or be withdrawn, and that may
      change or interrupt the service.
    </p>

    <h2>Termination</h2>
    <p>
      You may stop using the service and delete your account at any time from
      your dashboard. We may suspend accounts that violate these terms.
    </p>

    <h2>Disclaimer and liability</h2>
    <p>
      The service is provided "as is", without warranties of any kind to the
      extent permitted by law. To the maximum extent permitted by law, we are
      not liable for indirect or consequential losses, including lost profits
      or lost business arising from posts that fail to publish.
    </p>

    <h2>Contact</h2>
    <p>
      <?= legal_value('COMPANY_NAME', 'Company name') ?><br>
      <?= legal_value('COMPANY_ADDRESS', 'Company address') ?><br>
      <?= legal_value('COMPANY_CONTACT_EMAIL', 'Contact email') ?>
    </p>
  </div>
</main>
</body>
</html>
